### ISSUE TITLE
登录的ajax问题

### ISSUE THREAD

**Issue by pandongxia** [pandongxia/helenservice#4]
测试步骤：
1. 点首页的登录， 输入用户名:pandongxia， 密码：131420
2. modallogin.js中的alert显示是0，但是下面的变量$lg_success总是1

Expect:
当$lg_success是0时，modal框显示OK后退出，首页刷新

**Comment by tracker1984** [comment]
将modallogin.js的中代码$.ajax后面的代码移到$.ajax中的success里面，具体见代码。
case "login-form":
                //var $lg_username=$('#login_username').val();
                //var $lg_password=$('#login_password').val();
				var $lg_success = 1;				
				$.ajax({						
						type:"post",
						url:"doLogin",//"/myhs/Public/php/login.php",
						data: $('#login-form').serialize(),						
						success:function(res)
						{
							//alert(res.info);
							status = res.status;
							//alert('res:'+res);
							if (status == 0)
							{
								$lg_success = 0;
								//alert(res.msg);
								//window.location.replace("{:U('home/member/index')}");
							}
							else if (status == 2)
							{
								$lg_success = 2;
							}
							else if (status == 3) //error password
							{
								//alert('submit failed');
								$lg_success = 3;
							}
							else if (status == 1)
							{
								$lg_success = 1;
							}
							
							//alert('$lg_success:'+$lg_success);
			                if ($lg_success == 0) {
			                    msgChange($('#div-login-msg'), $('#icon-login-msg'), $('#text-login-msg'), "success", "glyphicon-ok", "Login OK");
			                    window.location.href = res.url;
			                } else if ($lg_success == 1) {
			                    msgChange($('#div-login-msg'), $('#icon-login-msg'), $('#text-login-msg'), "error", "glyphicon-remove", "Database error");
			                }
							 else if($lg_success == 2) {
			                    msgChange($('#div-login-msg'), $('#icon-login-msg'), $('#text-login-msg'),  "error", "glyphicon-remove", "Username doesn't exist");
			                }
							 else if($lg_success == 3) {
			                    msgChange($('#div-login-msg'), $('#icon-login-msg'), $('#text-login-msg'),  "error", "glyphicon-remove", "Error password");
			                }
			                return false;							

						}
				});
                break;

**Comment by pandongxia** [comment]
ok, good job!
